fix: goroutine leak on detectNetCodec()
This commit fixes a goroutine leak in the Worker, and adds a unit test
for leaked goroutines.

detectNetCodec() in worker_helper.go spawned a goroutine to wait on
`waitTimer.C`. However, a timer's channel is never closed if the timer
itself gets stopped. So, the goroutine would never finish waiting.
The usual solution to this issue in Go is to use an additional cancel
channel that lets the wait know that is should abort.

Warning: go.mod edited to add "go.uber.org/goleak"

A new unit test has been added to worket_test.go; it uses the library
"go.uber.org/goleak", which seems to be well regarded for goroutine leak
tests in the Go community.

Unit test output before this change:
```
    worker_test.go:125: found unexpected goroutines:
        [Goroutine 20 in state select, with github.com/jiyeyuran/mediasoup-go.detectNetCodec.func3 on top of the stack:
        github.com/jiyeyuran/mediasoup-go.detectNetCodec.func3()
                /home/work/mediasoup-go/worker_helper.go:81 +0x5f
        created by github.com/jiyeyuran/mediasoup-go.detectNetCodec in goroutine 19
                /home/work/mediasoup-go/worker_helper.go:80 +0x8eb
        ]
--- FAIL: TestWorkerClose_NoGoroutineLeaks (0.47s)
```

Unit test output after this change:
```
--- PASS: TestWorkerClose_NoGoroutineLeaks (0.03s)
```

worker_test.go instantiates a global worker, which never gets closed, so
that was also a source of goroutine leaks when running a single unit
test. This global worker was only used at one single point at
helper_test.go, so instead it seemed a good solution to just move there
the creation of the test worker.

channel.go and payload_channel.go had a break statement inside select
blocks, which were doing nothing and could be confusing, so they have
been deleted. The go compiler itself warned about them with this
message:
"ineffective break statement. Did you mean to break out of the outer loop? (SA4011) go-staticcheck"